name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  install:
    strategy:
      fail-fast: false

      matrix:
        type: [shared, static]

        os: [macos, ubuntu, windows]

        include:
          - { type: shared, build: YES }
          - { type: static, build: NO }

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
          -D BUILD_SHARED_LIBS=${{ matrix.build }}

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release --prefix prefix

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ matrix.type }}-${{ matrix.os }}
          path: prefix

  test:
    needs: install

    strategy:
      fail-fast: false

      matrix:
        type: [shared, static]

        os: [macos, ubuntu, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with: 
          name: ${{ github.sha }}-${{ matrix.type }}-${{ matrix.os }}
          path: prefix

      - name: Configure
        shell: pwsh
        run: >-
          $PWD = (Get-Location) -replace "\\", "/"

          & cmake -S test -B build -D CMAKE_BUILD_TYPE=Release
          -D "CMAKE_PREFIX_PATH=${PWD}/prefix"

          exit $LastExitCode

      - name: Build
        run: cmake --build build --config Release

      - name: Run
        working-directory: build
        run: ctest -C Release

  cleanup:
    if: always()

    needs: [install, test]

    runs-on: ubuntu-latest

    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            ${{ github.sha }}-shared-macos
            ${{ github.sha }}-static-macos
            ${{ github.sha }}-shared-ubuntu
            ${{ github.sha }}-static-ubuntu
            ${{ github.sha }}-shared-windows
            ${{ github.sha }}-static-windows
